=== carlosgarriga12/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
  <xs:element name="rutas">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ruta">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
        <xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
        <xs:element ref="duracion" />
        <xs:element ref="agencia" />
        <xs:element ref="descripcion" />
        <xs:element ref="personasAdecuadas" />
        <xs:element ref="lugarInicio" />
        <xs:element ref="direccionInicio" />
        <xs:element ref="coordenadas" />
        <xs:element ref="referencias" />
        <xs:element ref="hitos" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
      <xs:attribute name="tipo" type="xs:string" use="required" />
      <xs:attribute name="medioTransporte" type="xs:string" use="required" />
      <xs:attribute name="recomendacion" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaInicio" type="xs:date" />
  <xs:element name="horaInicio" type="xs:time" />
  <xs:element name="duracion" type="xs:string" />
  <xs:element name="agencia" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="personasAdecuadas" type="xs:string" />
  <xs:element name="lugarInicio" type="xs:string" />
  <xs:element name="direccionInicio" type="xs:string" />
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud" type="xs:decimal" />
  <xs:element name="latitud" type="xs:decimal" />
  <xs:element name="altitud" type="xs:decimal" />
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string" />
  <xs:element name="hitos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="descripcion" />
        <xs:element ref="coordenadas" />
        <xs:element ref="distanciaHitoAnterior" />
        <xs:element ref="fotografias" />
        <xs:element minOccurs="0" maxOccurs="1" ref="videos" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="distanciaHitoAnterior">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidadesDistancia" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="3" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografia" type="xs:string" />
  <xs:element name="video" type="xs:string" />
</xs:schema>

=== carlosgarriga12/SEW/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd" >
    <ruta nombre="Cueva de la Vaca – Mural de la Prehistoria Recorrido circular desde El Palmar" tipo="Senderismo" medioTransporte="A pie" recomendacion="8" >
        <duracion>3 horas y 20 minutos</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Caminata moderada. 
            Se necesita buena forma física. 
            Sendas de fácil acceso. 
            Para todos los niveles. 
            El punto de inicio de la Ruta es accesible en transporte público</descripcion>
        <personasAdecuadas>Personas con buena forma física</personasAdecuadas>
        <lugarInicio>Parada del Bus Viazul</lugarInicio>
        <direccionInicio>173-121 Rafael Trejo</direccionInicio>
        <coordenadas>
            <longitud>-83.71173819098695</longitud>
            <latitud>22.613662371370935</latitud>
            <altitud>146</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://www.komoot.com/es-es/smarttour/423387</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/vinales-mural-de-la-prehistoria-cueva-de-la-vaca-circular-95876954</referencia>
            <referencia>https://www.komoot.com/es-es/guide/2718679/rutas-de-senderismo-en-sierra-de-vinales</referencia>
        </referencias>
        <hitos>
            <hito nombre="Mirrador Aussichtspunkt">
                <descripcion>Excelentes vistas sobre el valle de Viñales</descripcion>
                <coordenadas>
                    <longitud>-83.71955634586483</longitud>
                    <latitud>22.599765064501455</latitud>
                    <altitud>185</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.0</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>miradorValles.jpeg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Cueva de la vaca">
                <descripcion>Puedes caminar por la cueva y continuar tu recorrido al otro lado del Mogote</descripcion>
                <coordenadas>
                    <longitud>-83.71731675873599</longitud>
                    <latitud>22.638450898014174</latitud>
                    <altitud>126</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.7</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>cuevaVaca.jpg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Mural de la prehistoria">
                <descripcion>Realmente impresionante y también se puede admirar desde lejos.</descripcion>
                <coordenadas>
                    <longitud>-83.74290835014092</longitud>
                    <latitud>22.61976036125839</latitud>
                    <altitud>190</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >5.46</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>muralPrehistoria.jpg</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Recorrido circular de senderismo desde Topes de Collantes" tipo="Senderismo" medioTransporte="A pie" recomendacion="8" >
        <duracion>2 horas y 4 minutos</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Caminata moderada. 
            Se necesita buena forma física. 
            Sendas de fácil acceso. Para todos los niveles. 
            El punto de inicio de la Ruta está junto a un aparcamiento.
        </descripcion>
        <personasAdecuadas>Personas con buena forma física</personasAdecuadas>
        <lugarInicio>Topes de Collante</lugarInicio>
        <direccionInicio>Topes de Collante, Cuba</direccionInicio>
        <coordenadas>
            <longitud>-80.01815662080142</longitud>
            <latitud>21.915225131956095</latitud>
            <altitud>760</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://es.wikiloc.com/rutas/senderismo/cuba/sancti-spiritus/topes-de-collantes</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/topes-de-collantes-sendero-salto-del-caburni-122641662</referencia>
            <referencia>https://oceanika.travel.blog/2018/04/17/parque-nacional-topes-de-collantes-ruta-por-el-salto-de-caburni/</referencia>
        </referencias>
        <hitos>
            <hito nombre="Hito 1">
                <descripcion>Es un punto aleatorio de la ruta</descripcion>
                <coordenadas>
                    <longitud>-80.01455298968486</longitud>
                    <latitud>21.918184398625744</latitud>
                    <altitud>750</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.0</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>hitoGenerico1.jpeg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Hito 2">
                <descripcion>Es un punto aleatorio de la ruta</descripcion>
                <coordenadas>
                    <longitud>-80.00848088046381</longitud>
                    <latitud>21.920673467078604</latitud>
                    <altitud>625</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.6</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>hitoGenerico2.jpg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Salto de caburni">
                <descripcion>Realmente impresionante y también se puede admirar desde lejos.</descripcion>
                <coordenadas>
                    <longitud>-80.00484199063916</longitud>
                    <latitud>21.921239870563042</latitud>
                    <altitud>190</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.4</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>caburni.jpeg</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Blick auf Vegas Grande – Wasserfall - Vegas Grande Recorrido circular desde El Chorrito" tipo="Senderismo" medioTransporte="A pie" recomendacion="8" >
        <duracion>1 hora y 17 minutos</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Caminata moderada. 
            Se necesita buena forma física. 
            Sendas de fácil acceso. 
            Para todos los niveles. 
            El punto de inicio de la Ruta es accesible en transporte público</descripcion>
        <personasAdecuadas>Personas con buena forma física</personasAdecuadas>
        <lugarInicio>El Chorrito</lugarInicio>
        <direccionInicio>El chorrito, Cuba, Topes de Collante</direccionInicio>
        <coordenadas>
            <longitud>-80.00848680291642</longitud>
            <latitud>21.904288405328725</latitud>
            <altitud>642</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://www.komoot.com/es-es/smarttour/423387</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/vinales-mural-de-la-prehistoria-cueva-de-la-vaca-circular-95876954</referencia>
            <referencia>https://www.komoot.com/es-es/guide/2718679/rutas-de-senderismo-en-sierra-de-vinales</referencia>
        </referencias>
        <hitos>
            <hito nombre="Puente">
                <descripcion>Escalera de madera</descripcion>
                <coordenadas>
                    <longitud>-80.00541279525686</longitud>
                    <latitud>21.905342724968182</latitud>
                    <altitud>650</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.0</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>kleine.jpg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Vista de vegas grande">
                <descripcion>Buenas vistas</descripcion>
                <coordenadas>
                    <longitud>-80.00327559789174</longitud>
                    <latitud>21.912929251203035</latitud>
                    <altitud>592</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >2.0</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>vistas.jpg</fotografia>
                </fotografias>
            </hito>
            <hito nombre="Cascadas de Vegas">
                <descripcion>Realmente impresionante y también se puede admirar desde lejos.</descripcion>
                <coordenadas>
                    <longitud>-80.0030154173518</longitud>
                    <latitud>21.9134120164646</latitud>
                    <altitud>550</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidadesDistancia="km" >0.1</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>cascadasVegas.jpg</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>
</rutas>
